pip install --user numpy

In [1]:
import numpy as np

In [2]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))
    
def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

# 1. Scalars, Vectors, Matricies


In [3]:
a = np.array(1.)
b = np.array([1.,2.,3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

Check

In [4]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



Dimmension

In [5]:
print_obj(a.ndim, "a.ndim")
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

a.ndim:
0

b.ndim:
1

c.ndim:
2



Shape

In [6]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")
print_obj(c.shape[0], "c.shape[0]")

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)

c.shape[0]:
2



# 2. Tensors

In [7]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [8]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



Q) 문제

[[[1], [2], [3]], [[4], [5], [6]]]의 shape는?

# 3. Defining Numpy Arrays

In [9]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b = np.zeros((2,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
c = np.full((2,2,2), 2)
c

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [12]:
d = np.random.random((2,3,4))
d

array([[[0.03268236, 0.9060004 , 0.93250689, 0.41577068],
        [0.87185253, 0.15208332, 0.75214191, 0.85732967],
        [0.57570465, 0.4635551 , 0.92549291, 0.81544879]],

       [[0.17787306, 0.11752518, 0.58077731, 0.07982408],
        [0.47066069, 0.24839922, 0.04327266, 0.11064811],
        [0.95097705, 0.71898001, 0.49628995, 0.89706121]]])

In [13]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
f = np.arange(0,10,0.5)
f

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
g = np.arange(10).astype(float).reshape(5,2)
g

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

Quiz)

0.0부터 23.0까지 채워진 (4,3,2) tensor를 만들어주세요

In [16]:
np.arange(24.).reshape(4,3,2)

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

# 4. Indexing & Slicing

### Indexing Array

In [17]:
a = np.arange(10)
print_obj(a, "a")

a:
[0 1 2 3 4 5 6 7 8 9]



In [18]:
print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7



In [19]:
print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]



In [20]:
print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]



Quiz)

- a[-4 :]의 값은?

- a[:-6]의 값은?

In [21]:
print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]



In [22]:
print_obj(a[::-1], "a[::-1]")
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]")

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]



Quiz)

a를 이용해서 [9,6,3]을 만들어주세요

### Indexing Matrix

In [23]:
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4



Quiz ) 

- 마지막 row에 접근하는 방법은?
- 2번째 column에 접근하는 방법은?
- [6,5]를 만드는 방법은?

### Conditional Indexing

In [24]:
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

idx = a % 2 == 0
print_obj(idx, "idx")

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]



Quiz)

a를 이용해서 [3,4,5]를 만드는 법은?

# 5. Math Operations

- 사칙연산

In [25]:
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [26]:
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)") # row wise
print_obj(a.sum(axis=1), "a.sum(axis=1)") # col wise = horizontal

print_obj(a.mean(), "a.mean()")
print_obj(a.max(), "a.max()")
print_obj(a.min(), "a.min()")


a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.max():
5

a.min():
0



Quiz)

a = np.arange(24).reshape((2,3,4)) 일 때, 마지막 차원의 관점에서의 합의 평균은?

In [27]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a.sum(axis = -1)

array([[ 6, 22, 38],
       [54, 70, 86]])

- dot product

In [29]:
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [30]:
a = np.arange(6).reshape((3, 2)) # (3*2) @ (2 *3) -> (3*3)
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



# 6. Shape Manipulation

In [31]:
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1)) # -1은 6으로만들고 남는 값으로 채움
print_obj(c, "c")

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]



Quiz) 

a.reshape(6,4,-1)의 shape는?

In [32]:
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]



Quiz)

np.ones((3,4))를 (3, 1, 1, 4)로 None을 이용해 만드는 방법은?

In [33]:
a = np.ones((3,4))
a[:,None,None].shape

(3, 1, 1, 4)

In [34]:
# Stack, concatenation
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]



In [35]:
print_obj(np.vstack([a, b]), "a,b vstack") # Vertical
print_obj(np.hstack([a, b]), "a,b hstack") # Horizontal
print_obj(np.hstack([a, b, a]), "a,b,a hstack") # 

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b,a hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]



In [36]:
print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0") # Generalization of vstack
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1") # Generalization of hstack

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



Quiz)

(4,3,2)와 (5,4,2)를 axis = 2의 관점에서 concat 할 수 있을까?

In [37]:
# Matrix transpose : 행렬 연산을 하기 위해서는 차원을 맞춰줄 필요가 있음
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [38]:
# Tensor transpose
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1])
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2])
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b's shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c's shape:
(3, 4, 2)



# 7. Broadcasting

In [39]:
a = np.arange(3)
b = 2.
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[0 1 2]

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [40]:
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[1 2]

a+b:
[[1 3]
 [3 5]
 [5 7]]



Quiz) 

a = np.arange(6).reshape((3,2))와 계산 불가능한 shape와 그 이유는?
- (2,1) Array
- (1,2) Array


In [41]:
# Tensor and matrix
a = np.arange(12).reshape((2,3,2))
b = np.arange(6).reshape((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(a+b, "a+b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]



Quiz)

a + b를 Broadcasting 할 수 있는 방법은?